### ISSUE TITLE
Not being redirected to MFA on login

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#204] opened 2019-06-20 02:55 UTC
With a fresh build of `cwp-installer 2.3`, MFA, and TOTP, I can't get the login form to redirect to the MFA registration screen.

By default, MFA should be optional but even when changing to required the registration flow won't appear.

This seems pretty odd, so may be done to my local set up - but if someone is spinning up a new site, it would be good to check this issue.

**Comment by brynwhyman** [comment] 2019-06-20 02:56
Note, I can still view the MFA modal in the CMS profile area

**Comment by robbieaverill** [comment] 2019-06-20 07:21
I can reproduce this in CWP, and the unit test suite for MFA fails in the CWP installer as well, which is a good sign for us to debug.

This is because the "can view CMS controllers" check is returning false. I suspect it's related to subsite's alternate permission check logic, but can't confirm that yet.

**Comment by robbieaverill** [comment] 2019-06-23 22:15
It looks like the `LeftAndMainSubsites::canAccess()` check isn't working, because the Member has not been set to `Security` yet. MFA delays this, so it can perform MFA first. Investigating workarounds...

**Comment by robbieaverill** [comment] 2019-06-23 22:25
Yeah this was a subsites bug, fix at https://github.com/silverstripe/silverstripe-subsites/pull/430

**Comment by NightJar** [comment] 2019-06-23 23:50
Closed in the above referenced pull request.

**Comment by brynwhyman** [comment] 2019-06-24 05:13
Reopening this. With `silverstripe/subsites (2.3.x-dev b3bd51c)` installed, CMS Administrators are shown the MFA screen, but users with Content Author permissions still aren't redirected to MFA.

**Comment by robbieaverill** [comment] 2019-06-24 23:54
Ah, I fixed this yesterday with https://github.com/silverstripe/silverstripe-mfa/pull/212 but didn't reference any issues from that PR

**Comment by brynwhyman** [comment] 2019-06-25 00:02
Ah, thanks. I saw that PR but from the title thought it wasn't relevant to this. Nice one!

**Closed** 2019-06-25 21:24 UTC
