### ISSUE TITLE
Cannot alter multiple MFA in CMS settings without refresh

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#172] opened 2019-06-09 23:53 UTC
### Description
I'm unable to update multiple MFA settings in the CMS without refreshing the page. 

Console error:
`Uncaught (in promise) Error: Could not delete method. Error code 400. Errors: - Request timed out, please try again - at bundle-cms.js?m=1560115486:1`

### To recreate
1. Ensure the user has full CMS access permissions, so not to see the bug #171
2. Access `/admin/myprofile`
3. Select 'Reset' recovery codes and follow the process
4. Attempt to complete another MFA settings action such as 'Remove' an authenticator app
5. Identify the bug and the error quoted above.

### Expected result
It's expected that a user is able to complete multiple MFA settings updates within one visit to `/admin/myprofile` without failure or the need to refresh the page.

### Notes
- ~Attempted a 'refresh' by using the better button to skip to the next user profile and (back again), in this case I still experienced the bug.~

**Comment by ScopeyNZ** [comment] 2019-06-10 07:46
You shouldn't even _have_ the ability to reset/delete other users. Do you have "better buttons" on "My Profile"?

**Comment by brynwhyman** [comment] 2019-06-10 21:50
Yeah, sorry, ingore my comment about better buttons. That should be on another issue.

**Comment by brynwhyman** [comment] 2019-06-10 22:08
After the first action it might not be updating the redux store with the new security ID

**Comment by robbieaverill** [comment] 2019-06-17 23:47
Yeah - I'm not sure that we actually bind (via `connect`) to the redux store, but rather access it directly when the component is mounted. If it changes in the store it won't necessarily change in the component, so we'd need to build this into a mapStateToProps somewhere instead.

**Comment by robbieaverill** [comment] 2019-06-18 04:26
I can't reproduce this any more, it may have been fixed with another PR since raised.

From my testing I can go to my profile, add or remove any or all of my methods, reset backup codes and methods, and everything works.

Feel free to reopen if you find it happens again with up-to-date codebases.

**Closed by robbieaverill** 2019-06-18 04:26 UTC
