### ISSUE TITLE
New user in group with limited permissions cannot login

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-mfa#369] opened 2019-11-27 22:47 UTC
Scenario
- MFA is required i.e. non-optional
- Newly setup user.
- Member is assigned to a single group. 
- That group that has the following permissions:
  1. Access a custom ModelAdmin
  2. Access the files section

When attempting to access the CMS, user is prompted to enter username/password, get redirect back to that enter credentials screen with empty username/password fields.  Never get prompted to setup MFA. URL is:
/Security/login?BackURL=%2Fadmin%2Fpages%2F 

If use a different browser and instead of going to /admin go to /admin/mymodeladmin or /admin/files, then experience is exactly the same, however the ?BackURL equals %2Fadmin%2Fmymodeladmin%2F

If I also add the default "Content Author" group to the new user, then they can login to /admin and setup MFA

### Pull requests
- [x] SS4: https://github.com/silverstripe/silverstripe-mfa/pull/375
- [x] SS3: https://github.com/silverstripe/silverstripe-mfa/pull/382

**Comment by michalkleiner** [comment] 2019-11-28 01:25
Thanks for reporting the issue. This is quite a common scenario for us as well, so we'd keep our eyes peeled for a solution here.

**Comment by robbieaverill** [comment] 2019-11-28 01:25
This should be covered under the "does the user have access to the CMS" check. Unfortunately that logic is more complicated than it could be (there's no `$member->hasCMSAccess()` method, you have to check many different permission codes across different controllers).

Here's the relevant code: https://github.com/silverstripe/silverstripe-mfa/blob/4/src/Service/EnforcementManager.php#L224-L245

Do you have subsites running as well? We've had trouble with those two conflicting before.

**Comment by ericgsmith** [comment] 2019-11-28 02:03
@robbieaverill I can confirm the site we have this issue on is also running subsites.

**Comment by robbieaverill** [comment] 2019-11-28 02:12
@ericgsmith can you share which versions you're using for silverstripe/mfa and silverstripe/subsites please?

**Comment by ericgsmith** [comment] 2019-11-28 02:39
@robbieaverill - ah looks like we might be a couple behind.

On 2.3.2 for subsites and 4.0.0-rc2 for mfa - will update & let you know if the issue still persists on latest

**Comment by brynwhyman** [comment] 2019-11-28 03:43
Hey @emteknetnz can you also please confirm the versions of subsites, MFA, and core that your reported site is running?

**Comment by emteknetnz** [comment] 2019-11-28 20:06
mfa is 4.0.0-rc2, framework is 4.4.3, subsites is 2.3.2

**Comment by robbieaverill** [comment] 2019-11-28 20:11
@emteknetnz try using subsites 2.3.3 and MFA 4.0.2

The relevant fix for this issue in subsites is here: https://github.com/silverstripe/silverstripe-subsites/commit/4fdf2e24e328c714b571d47b5dfb5b64fc5c185b

**Comment by ericgsmith** [comment] 2019-11-28 23:56
Hi all - the issue still persists for us using subsites 2.3.3 and MFA 4.0.2.

Looking at the logs, I see the following 2 sequential log messages after clicking login.

2019-11-29 12:49:04.000 INFO: "xxx@pikselin.com" (ID: 132) successfully logged out []
2019-11-29 12:49:04.000 INFO: "xxx@pikselin.com" (ID: 132) successfully logged in []

**Comment by brynwhyman** [comment] 2019-11-29 00:52
Thanks for confirming. While the description notes this, it wasn't immediately clear to me:

* A user with these limited permissions gets the log in loop when MFA is `required`, (not `optional`). 
* If MFA is `optional`, the user can successfully log in, but they're never shown the MFA registration screen.

**Comment by brynwhyman** [comment] 2019-11-29 00:56
I'm marking this as a critical bug. With this module installed it's reasonable to expect that the basic flow of 'requiring MFA' works for all users with some form of CMS access, e.g. the Files area.

**Comment by robbieaverill** [comment] 2020-03-23 01:17
The culprit is this line: https://github.com/silverstripe/silverstripe-admin/blob/1/code/LeftAndMain.php#L1007-L1010. It's not new and I'm not sure why we didn't notice it earlier, but MFA doesn't log the user in at the point where we use this API, so the member is null, menu items empty, nothing to check permissions against.

I'm working on a PR now.

**Comment by Cheddam** [comment] 2020-03-26 00:38
Resolved in #375, released in `4.0.5`. A `3.0.x` release will follow.

**Comment by brynwhyman** [comment] 2020-03-26 20:14
Hey @Cheddam, it doesn't look like this made it to `3.0` as well? Re-opening for now.

**Closed** 2020-07-15 21:33 UTC
Labels: affects/v3, effort/medium, impact/critical, type/bug
