### ISSUE TITLE
Add Login Forms module as a dependency

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-mfa#138] opened 2019-05-26 21:16 UTC
Since our styles are being built against the logins-forms UI, we should mark it as a direct dependency to make sure it's present. Developers can overload / disable the login-forms module if they want to adjust the rendering.

**Comment by robbieaverill** [comment] 2019-05-26 21:21
Duplicate of https://github.com/silverstripe/silverstripe-mfa/issues/95 =)

**Closed by robbieaverill** 2019-05-26 21:21 UTC
Labels: affects/v4, effort/easy, impact/high, type/enhancement
